config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]

    collection do
      get 'search'
      end
  end
  
  resources :users, only: [:edit, :index, :show, :update] do
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # @comment = Comment.create(comment_params)
    # @comment.save
    # render :create
    # redirect_to post_path(params[:post_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id 
    @comments = @post.comments.includes(:user).order("created_at DESC")

  if @comment.save
    render :create
  end
    
  end
  


  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comments = @post.comments.includes(:user).order("created_at DESC")
    @comment.destroy
    render :destroy
    
    # comment = Comment.find(params[:id])
    # post = comment.post
    # comment.destroy
    # redirect_to "/posts/#{post.id}"
  end

  

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
- @comments.each do |comment|
  .comment-list-container
    .left-box-name-text
      .comment_user_name
        = link_to comment.user.nickname, "/users/#{comment.user_id}"
      .comment.text
        = comment.text
      .comment-created-time
        = comment.created_at.strftime('%Y/%m/%d')
    - if user_signed_in? && current_user.id == @post.user_id
      .comment_delete_btn
        = link_to post_comment_path(@post, comment.id), method: :delete, remote: true do
          %i.fas.fa-trash-alt

app/views/comments/create.js.erb
$("#comments-event").html("<%= j(render 'comments/comment', comment: @comments) %>")
$("textarea").val('')

app/views/comments/destroy.js.erb
$("#comments-event").html("<%= j(render 'comments/comment', comment: @comments) %>")
$("textarea").val('')