config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]

    collection do
      get 'search'
      end
  end
  
  resources :users, only: [:edit, :index, :show, :update] do
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  mount_uploader :profile_image, ImageUploader



  validates :nickname, presence: true, uniqueness: true
  validates :profile_text, length: { maximum: 200 }

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', nickname: 'guestさん', last_name_kanji: 'guest_last_name', first_name_kanji: 'guest_first_name') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
 

  
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:last_name_kanji,:first_name_kanji,:profile_image,:profile_text,:avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname,:profile_image,:profile_text,:avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  class Users::SessionsController < Devise::SessionsController
    def new_guest
      user = User.guest
      sign_in user
      redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
    end
  end
  
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to user_path
    else
      render :edit 
    end
  end

  def create
    post = Post.new(post_params)
    post.save
    redirect_to user_path
  end

  def show
    
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :profile_image, :profile_text)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "マイページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :プロフィール画像
        .FormField__input--normal
          = f.file_field :profile_image, class: 'account_profile_image', id: 'upload-icon'
      .user_name
        = current_user.nickname
      .FormField
        .FormField__label--normal
          = f.label :ニックネーム
        .FormField__input--normal
          = f.text_field :nickname, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :メールアドレス
        .FormField__input--normal
          = f.email_field :email
      .FormField
        .FormField__label--normal
          = f.label :自己紹介
        .FormField__profile__text
          = f.text_area :profile_text, autofocus: true, maxlength: "150"
      
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
= render partial: "layouts/header"

.main_profile_contents
  .profile_image_content
    .profile_image-pic
      - if @user.profile_image?
        = image_tag @user.profile_image.to_s
      - else
        = image_tag current_user.avatar.to_s
      
  .profile_main_content
    .profile_user_box
      .profile_user_name
        =  @user.nickname
      - if user_signed_in? && current_user.id == @user.id
        .profile_edit_btn
          = link_to 'プロフィールを編集', edit_user_path(@user), method: :get
    .profile_user_text
      =  @user.profile_text
- @posts.each do |post|
  .post_mainscreen
    .post_header
      .user_profile_image
        - if post.user.profile_image?
          = image_tag post.user.profile_image.to_s
        - else
          = image_tag current_user.avatar.to_s
      .user_nickname
        = post.user.nickname
      .post_title_box
        .post_title_name
          = post.title
      .post-controll-btn
        .like_btn{id: "likes_buttons_#{post.id}"}
          = render partial: "likes/like", locals: {post: post}
        .comment_icon
          = link_to post_path(post.id), method: :get do
            %i.far.fa-comment
        %ul.options-post
          = icon('fa', 'ellipsis-h')
          - if user_signed_in? && current_user.id == @user.id
            %li.delete_link
              = link_to '削除', post_path(post.id), method: :delete
            %li.edit_link
              = link_to '編集', edit_post_path(post.id), method: :get

    .post__content
      - if post.image.present?
        .post__content--pic
          = image_tag post.image.to_s
        .post__content--textbox
          .user_nickname
            = post.user.nickname
          .post-created-time
            = post.created_at.strftime("%Y-%m-%d%H:%M")
          .post__content--text
            = post.text
      - else
        .post__content--textbox
          .user_nickname
            = post.user.nickname
          .post-created-time
            = post.created_at.strftime("%Y-%m-%d%H:%M")
          .post__content--text
            = post.text

= render partial: "layouts/footer"
  
  