config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]

    collection do
      get 'search'
      end
  end
  
  resources :users, only: [:edit, :index, :show, :update] do
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  

  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

  def like(user)
    likes.create(user_id: user.id)
  end

  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_post, only: [:edit, :show]

  include PostsHelper

  def index
    @posts = Post.all.order(created_at: :desc)
    @like = Like.new
    @post = Post.find_by(params[:id])
  end

  


  def new
    @post = Post.new  
  end

  def create
     post = Post.create(post_params)
     if post.save
        redirect_to root_path
     else
        render :create
     
     end
  end

  def search
    redirect_to search_path if params[:keyword] == ""
    @posts = Post.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%").order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end 

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
  end
  
  def update
    post = Post.find(params[:id])
    post.update(post_params)
    if post.save
      redirect_to root_path
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  private
  def post_params
    params.require(:post)
          .permit(:title, :text, :image)
          .merge(user_id: current_user.id)
  end
end

def set_post
  @post = Post.find(params[:id])
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def translator(text)
    project_id = ENV["august-upgrade-288810"]
    translate = Google::Cloud::Translate.new version: :v2, project_id: project_id
    if text =~ /(?:\p{Hiragana}|\p{Katakana}|[一-龠々])/
      @text = text
      target = "en"
      @translation = translate.translate @text, to: target
    else
      @text = text
      target = "ja"
      @translation = translate.translate @text, to: target

    end

  end
end

app/views/posts/destroy.html.haml
.header
  .header_functions
    .left__part
      .logomark_app
        = image_tag asset_path("GElogo.png"), size: "80x80", class: "ge_logo" 
      .logo__title GUNJIN ENGLSIH
    .middle_part
      .home-header__search-box
  .delete-complete-message
    .delete-message-box
      %p 投稿は削除されました。
    .back-toppage-btn
      = link_to '投稿一覧へ戻る', root_path
      

app/views/posts/edit.html.haml
.function-row
  %h2 編集する 
.form_newpost
  = form_with model: @post do |form|
    .form-title-box
      = form.label :タイトルを入力してください!
      = form.text_field :title, class: "title-input-form" 
    .form-text-box
      = form.label :気になることを質問しよう!
      = form.text_area :text, rows: "10", class: "text-content"
      = form.label :image, class: 'Form__inputImage' do
        = icon('far', 'image', class: 'Form__icon')
        = form.file_field :image, class: 'Hidden'
    .form-send-btn
      = form.submit "編集する", class: "newpost_submitbtn"

app/views/posts/index.html.haml
= render partial: "layouts/header"
.wrapper 
  - @posts.each do |post|
    .post_mainscreen
      .post_header
        .user_profile_image
          - if post.user.profile_image?
            = link_to image_tag(post.user.profile_image.to_s), user_path(post.user_id), method: :get
          - else
            = link_to image_tag(post.user.avatar.to_s), user_path(post.user_id), method: :get
        .user_nickname
          = post.user.nickname
        .post_title_box
          .post_title_name
            = post.title
        .post-controll-btn
          .like_btn{id: "likes_buttons_#{post.id}"}
            = render partial: "likes/like", locals: {post: post}
          .comment_icon
            = link_to post_path(post.id), method: :get do
              %i.far.fa-comment
          %ul.options-post
            = icon('fa', 'ellipsis-h')
            - if user_signed_in? && current_user.id == post.user_id
              %li.delete_link
                = link_to '削除', post_path(post.id), method: :delete
              %li.edit_link
                = link_to '編集', edit_post_path(post.id), method: :get

      .post__content
        - if post.image.present?
          .post__content--pic
            = image_tag post.image.to_s
          .post__content--textbox
            .user_nickname
              = post.user.nickname
            .post-created-time
              = post.created_at.strftime('%Y/%m/%d')
            .post__content--text
              = post.text
            %input{ type: "checkbox", id: "label1", class: "chenge-btn" }
            -# .translate-btn
            -#   %label cheat?
            .post__content--text--english
              = translator(post.text)
        - else
          .post__content--textbox
            .user_nickname
              = post.user.nickname
            .post-created-time
              = post.created_at.strftime('%Y/%m/%d')
            .post__content--text
              = post.text
            %input{ type: "checkbox", id: "label1", class: "chenge-btn" }
            -# .translate-btn
            -#   %label cheat?
            .post__content--text--english
              = translator(post.text)
        
= render partial: "layouts/footer"

app/views/posts/new.html.haml
.function-row
  %h2 投稿する
.form_newpost
  = form_with model: @post do |form|
    .form-title-box
      = form.label :タイトルを入力してください！（２０文字以内）
      = form.text_field :title, class: "title-input-form", autofocus: true, maxlength: "20"
    .form-text-box
      = form.label :気になることを質問しよう！（255文字以内）
      = form.text_area :text, rows: "5", class: "text-content", autofocus: true, maxlength: "255"
      = form.label :image, class: 'Form__inputImage' do
        = icon('far', 'image', class: 'Form__icon')
        = form.file_field :image, class: 'Hidden'
    .form-send-btn
      = form.submit "投稿する", class: "newpost_submitbtn"

app/views/posts/search.html.haml
= render partial: "layouts/header"

- @posts.each do |post|
  .post_mainscreen
    .post_header
      .user_profile_image
        - if post.user.profile_image?
          = link_to image_tag(post.user.profile_image.to_s), user_path(post.user_id), method: :get
        - else
          = link_to image_tag(current_user.avatar.to_s), user_path(post.user_id), method: :get 
      .user_nickname
        = post.user.nickname
      .post_title_box 
        .post_title_name
          = post.title
      .post-controll-btn
        .like_icon
          = icon('far', 'heart')
        .comment_icon
          = link_to post_path(post.id), method: :get do
            %i.far.fa-comment
        %ul.options-post 
          = icon('fa', 'ellipsis-h')
          %li.comment_link
            = link_to 'コメント', post_path(post.id), method: :get
          - if user_signed_in? && current_user.id == post.user_id
            %li.delete_link
              = link_to '削除', post_path(post.id), method: :delete
            %li.edit_link
              = link_to '編集', edit_post_path(post.id), method: :get
              
    .post__content
      - if post.image.present?
        .post__content--pic
          = image_tag post.image.to_s
        .post__content--textbox
          .user_nickname
            = post.user.nickname
          .post__content--text
            = post.text
      - else
        .post__content--textbox
          .user_nickname
            = post.user.nickname
          .post__content--text
            = post.text
        
= render partial: "layouts/footer"

app/views/posts/show.html.haml
= render partial: "layouts/header"
  
.post_mainscreen
  .post_header
    .user_profile_image
      - if @post.user.profile_image?
        = link_to image_tag(@post.user.profile_image.to_s), user_path(@post.user_id), method: :get
      - else
        = link_to image_tag(current_user.avatar.to_s), user_path(@post.user_id), method: :get
    .user_nickname
      = @post.user.nickname
    .post_title_box 
      .post_title_name
        = @post.title
    .post-controll-btn
      .like_btn{id: "likes_buttons_#{@post.id}"}
        = render partial: "likes/like", locals: {post: @post}
      %ul.options-post 
        = icon('fa', 'ellipsis-h')
        - if user_signed_in? && current_user.id == @post.user_id
          %li.delete_link
            = link_to '削除', post_path(@post.id), method: :delete
          %li.edit_link
            = link_to '編集', edit_post_path(@post.id), method: :get
        
  .post__content
    - if @post.image.present?
      .post__content--pic
        = image_tag @post.image.to_s
      .post__content--textbox
        .user_nickname
          = @post.user.nickname
        .post-created-time
          = @post.created_at.strftime('%Y/%m/%d')
        .post__content--text
          = @post.text
    - else
      .post__content--textbox
        .user_nickname
          = @post.user.nickname
        .post-created-time
          = @post.created_at.strftime('%Y/%m/%d')
        .post__content--text
          = @post.text

  .comment__box
    - if current_user
      = form_with model: [@post, @comment], id: "new_comment", remote: true do |form|
        = form.text_area :text, placeholder: "コメントする", class: "comment-form-box"
        = form.submit "投稿する", class: "comment-btn"
      .comment-lists{id: "comments-event"}
        = render partial: "comments/comment", locals: {comment: @comments}
    - else
      %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
            
= render partial: "layouts/footer"
        