config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]

    collection do
      get 'search'
      end
  end
  
  resources :users, only: [:edit, :index, :show, :update] do
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/views/layouts/_footer.html.haml
.footer
  .contents
    %ul.contents
      %li.content
        %h2.content__head GE COMPANY
        %ul
          %li.content= link_to '会社概要','/'
          %li.content= link_to 'プライバシーポリシー','/'
      %li.content
        %h2.content__head 言語一覧
        %ul
          %li.content= link_to '英語','/'
          %li.content= link_to '中国語','/'
          %li.content= link_to 'スペイン語','/'
          %li.content= link_to 'フランス語','/'
          %li.content= link_to 'イタリア語','/'   
      %li.contect
        %h2.content__head ヘルプ＆ガイド
        %ul
          %li.content= link_to 'アプリガイド','/'
          %li.content= link_to 'お知らせ','/'

app/views/layouts/_header.html.haml
.header
  .header_functions
    .left__part
      .logomark_app
        = link_to image_tag(asset_path("GElogo.png"), size: "80x80", class: "ge_logo"), root_path
      .logo__title GUNJINSAN ENGLSIH
    .middle_part
      .home-header__search-box
        = form_with(url: search_posts_path, local: true, method: :get, class: "form") do |form|
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "searchbox-input"
        = link_to search_posts_path do
          %button{type: "submit"}
            .search-btn
              = icon('fa','search')
    .right__part
      - if user_signed_in?
        .user_btn_logout_post
          = link_to "ログアウト", destroy_user_session_path, class: "post", method: :delete
        .user_btn_logout_post
          = link_to "投稿する", new_post_path, class: "post"
        .user_profile_image-header
          - if current_user.profile_image?
            = link_to image_tag(current_user.profile_image.to_s), user_path(current_user.id), method: :get
          - else
            = link_to image_tag(current_user.avatar.to_s), user_path(current_user.id), method: :get
      - else
        .user_btn_login_sign_up
          = link_to 'ゲスト用', users_guest_sign_in_path, method: :post, class: "post"
        .user_btn_login_sign_up
          = link_to "ログイン", new_user_session_path, class: "post"
        .user_btn_login_sign_up
          = link_to "新規登録", new_user_registration_path, class: "post"
    
          
        
  

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GeApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield